"""empty message

Revision ID: fd7c347d30bc
Revises: 
Create Date: 2020-06-03 22:57:57.248873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7c347d30bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artistlocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seekingtalent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeking_talent', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seekingvenu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeking_venue', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venuelocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_venue', sa.String(length=120), nullable=False),
    sa.Column('state_venue', sa.String(length=120), nullable=False),
    sa.Column('street_number', sa.Integer(), nullable=False),
    sa.Column('street_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=False),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website_link', sa.String(length=120), nullable=True),
    sa.Column('loction_id', sa.Integer(), nullable=False),
    sa.Column('Seeking_venu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Seeking_venu_id'], ['seekingvenu.id'], ),
    sa.ForeignKeyConstraint(['loction_id'], ['artistlocation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('venue_location_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=False),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website_link', sa.String(length=120), nullable=True),
    sa.Column('seeking_talent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seeking_talent_id'], ['seekingtalent.id'], ),
    sa.ForeignKeyConstraint(['venue_location_id'], ['venuelocation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artisimiddlename',
    sa.Column('middlename_id', sa.Integer(), nullable=False),
    sa.Column('middlename', sa.String(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('middlename_id'),
    sa.UniqueConstraint('artist_id')
    )
    op.create_table('artistgenres',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genres')
    )
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('star_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venuegenres',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genres')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venuegenres')
    op.drop_table('show')
    op.drop_table('artistgenres')
    op.drop_table('artisimiddlename')
    op.drop_table('venue')
    op.drop_table('artist')
    op.drop_table('venuelocation')
    op.drop_table('seekingvenu')
    op.drop_table('seekingtalent')
    op.drop_table('artistlocation')
    # ### end Alembic commands ###
